Team-I1lI1I1l-as-barcode/FluffyTime-backend

build.gradle
src/main/java/com/fluffytime/comment/controller/CommentController.java
src/main/java/com/fluffytime/comment/controller/api/CommentRestController.java
src/main/java/com/fluffytime/comment/dto/CommentRequestDto.java
src/main/java/com/fluffytime/comment/dto/CommentResponseDto.java
src/main/java/com/fluffytime/comment/repository/CommentRepository.java
src/main/java/com/fluffytime/comment/service/CommentService.java
src/main/java/com/fluffytime/domain/Comment.java
src/main/java/com/fluffytime/domain/User.java
src/main/resources/application.yml
src/main/resources/static/css/comment/comment.css
src/main/resources/static/html/comment/test.html
src/main/resources/static/js/comment/testscripts.js

feat: 댓글 생성 기능

---

build.gradle
src/main/java/com/fluffytime/config/SecurityConfig.java
src/main/java/com/fluffytime/domain/Role.java
src/main/java/com/fluffytime/domain/User.java
src/main/java/com/fluffytime/domain/UserRole.java
src/main/java/com/fluffytime/join/common/ResponseCode.java
src/main/java/com/fluffytime/join/controller/api/joinApiController.java
src/main/java/com/fluffytime/join/controller/joinController.java
src/main/java/com/fluffytime/join/reponse/JoinResponseDto.java
src/main/java/com/fluffytime/join/reponse/ResponseDto.java
src/main/java/com/fluffytime/join/repository/RoleRepository.java
src/main/java/com/fluffytime/join/repository/UserRepository.java
src/main/java/com/fluffytime/join/request/JoinRequestDto.java
src/main/java/com/fluffytime/join/service/JoinService.java
src/main/resources/application.yml
src/main/resources/static/html/join/joinForm.html
src/main/resources/static/html/join/success.html
src/main/resources/static/js/join/join.js

회원가입 유저정보저장 기능 구현
/api/users/join 을 통해 받아온 유저정보를 DB에 저장합니다.
이메일검증, 유저명 검증 기능은 추후 개발예정

feat: 회원가입 유저정보저장

---

src/main/java/com/fluffytime/config/SecurityConfig.java
src/main/java/com/fluffytime/domain/Profile.java
src/main/java/com/fluffytime/myPage/controller/api/MyPageRestController.java
src/main/java/com/fluffytime/myPage/dto/ErrorResponseDto.java
src/main/java/com/fluffytime/myPage/dto/MyPageResponseDto.java
src/main/java/com/fluffytime/myPage/dto/PostDto.java
src/main/java/com/fluffytime/myPage/dto/ProfileResponseDto.java
src/main/java/com/fluffytime/myPage/exception/MyPageException.java
src/main/java/com/fluffytime/myPage/exception/MyPageExceptionCode.java
src/main/java/com/fluffytime/myPage/exception/MyPageExceptionResponseHandler.java
src/main/java/com/fluffytime/myPage/service/MyPageService.java
src/main/resources/static/css/mypage/profiles/edit.css
src/main/resources/static/html/mypage/mypage.html
src/main/resources/static/html/mypage/profiles/edit.html
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/mypage/profiles/profile.js

- 마이페이지의 프로필화면의 기본적인 뼈대를 구성
- API를 이용해 프로필에 정보를 불러오는데 성공
- 마이페이지와 프로필의 예외처리 구현

Feature/마이페이지 프로필화면 구현

---

src/main/java/com/fluffytime/comment/controller/CommentController.java
src/main/java/com/fluffytime/comment/controller/api/CommentRestController.java
src/main/java/com/fluffytime/comment/dto/CommentRequestDto.java
src/main/java/com/fluffytime/comment/dto/CommentResponseDto.java
src/main/java/com/fluffytime/comment/repository/CommentRepository.java
src/main/java/com/fluffytime/comment/service/CommentService.java
src/main/java/com/fluffytime/config/SecurityConfig.java
src/main/java/com/fluffytime/domain/Comment.java
src/main/java/com/fluffytime/post/repository/PostRepository.java
src/main/java/com/fluffytime/user/repository/UserRepository.java
src/main/resources/application.yml
src/main/resources/static/html/comment/testView.html
src/main/resources/static/js/comment/testscripts.js

feat: 댓글 생성 기능 복사

---

src/main/java/com/fluffytime/mypage/controller/api/MyPageRestController.java
src/main/java/com/fluffytime/mypage/response/RequestResultDto.java
src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/resources/static/html/mypage/profiles/profile.html
src/main/resources/static/js/mypage/profiles/profile.js

회원 탈퇴 버튼 클릭 시 "계정이 영구 삭제됩니다. 정말 탈퇴하시겠습니까?" 기능을 구현합니다.
resolved #36

feat : 회원 탈퇴 기능 구현

---

src/main/java/com/fluffytime/search/controller/SearchController.java
src/main/java/com/fluffytime/search/controller/api/SearchRestController.java
src/main/java/com/fluffytime/search/dto/request/Request.java
src/main/resources/static/html/search/search.html
src/main/resources/static/js/search/search.js

검색화면 기본 뼈대 구현

---

src/main/java/com/fluffytime/explore/controller/api/ExploreRestController.java
src/main/java/com/fluffytime/explore/dto/ExploreResponseDto.java
src/main/java/com/fluffytime/explore/exception/ExploreErrorCode.java
src/main/java/com/fluffytime/login/jwt/util/JwtTokenizer.java
src/main/resources/application.yml
src/main/resources/static/css/explore/explore.css
src/main/resources/static/html/explore/explore.html
src/main/resources/static/js/explore/explore.js
src/main/resources/static/js/join/join.js

feat: 탐색 페이지 무한 스크롤 구현
탐색 페이지 무한 스크롤 구현, 더이상 가져올 데이터가 없으면 스크롤 인식을 멈추는 기능 추가

Feature/탐색 탐색화면구현

---

src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/html/mypage/mypage.html
src/main/resources/static/html/mypage/profiles/profile.html
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/mypage/profiles/profile.js

- **게시물이 있을 때**
- 게시물 나열을 위한 CSS 구현
- 게시물 표시 로직을 수정하는 JavaScript 추가
- **게시물이 없을 때**
- 게시물 추가를 유도하는 CSS 구현
- 게시물 추가 로직을 수정하는 JavaScript 추가
- **프로필 사진 관련**
- 마이페이지에서 프로필 사진 클릭 시 사진 업데이트 기능 제공
- 프로필 사진에 블러 효과 적용
- 프로필 사진에 카메라 아이콘 추가
- 프로필 사진 영역 클릭 시 사진 업데이트 기능 활성화
-  **사진 변경 버튼 클릭 시**
- 모달창이 열리도록 구현
- 사진 업로드, 현재 사진 삭제, 취소
- **반려동물 성별**
- 성별에 따라 기존 텍스트에서 기호로 나타나도록 표현
- **기타 버그 수정**
- 프로필 정보 수정시 제출 버튼이 활성화 되지 않는 오류 해결

Feature/마이페이지 화면 구현

---

src/main/resources/static/js/search/search.js

window.onload = selectTab(currentTab);
추가

fix: 검색 화면 페이지 처음 로드시 검색이 안되던 오류 해결

---

src/main/java/com/fluffytime/config/SecurityConfig.java
src/main/java/com/fluffytime/mypage/request/PostDto.java
src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/java/com/fluffytime/post/controller/PostController.java
src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/userpage/userpage.js

2차 통합 후 포스트 관련 기능 연결과 프로필 관련 버그를 수정합니다
- 게시물이 없을때 + 이미지 클릭시 게시글 등록 창으로 이동
- 게시물 등록시 기존 content 출력에서 각 게시물의 첫번째 이미지를 썸네일로 설정
- 프로필과 유저의 양방향 관계로 변경함에 따라 프로필 등록 및 수정 관련 service 로직 수정

fix : 포스트 기능 연결  및 프로필 관련 버그 수정

---

src/main/resources/static/css/home/home.css
src/main/resources/static/css/styles.css
src/main/resources/static/html/comment/testView.html
src/main/resources/static/html/index.html
src/main/resources/static/js/home/home.js

Feature/공통 홈

---

src/main/java/com/fluffytime/config/SecurityConfig.java
src/main/java/com/fluffytime/explore/controller/api/ExploreRestController.java
src/main/java/com/fluffytime/login/jwt/util/JwtTokenizer.java
src/main/java/com/fluffytime/post/controller/PostController.java
src/main/java/com/fluffytime/post/controller/api/PostRestController.java
src/main/resources/static/js/explore/explore.js

getFirst()에서 발생하던 예외를 optional로 처리함

fix: 탐색 페이지에서 사진이 들어가지 않던 오류 해결

---

src/main/resources/static/html/index.html
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/home/home.js
src/main/resources/static/js/post/createPost.js

사이드바, post detail 경로, 댓글 리로드 수정

fix: 사이드바, post detail 경로, 댓글 리로드

---

src/main/java/com/fluffytime/post/controller/PostController.java
src/main/java/com/fluffytime/post/controller/api/PostRestController.java
src/main/java/com/fluffytime/post/service/PostService.java
src/main/resources/static/css/post/createPost.css
src/main/resources/static/html/index.html
src/main/resources/static/html/post/createPost.html
src/main/resources/static/js/post/createPost.js
src/main/resources/static/js/post/postDetail.js

fix: 모달창 수정

---

src/main/java/com/fluffytime/login/jwt/filter/CustomLoginFilter.java
src/main/java/com/fluffytime/login/jwt/filter/JwtAuthenticationFilter.java
src/main/resources/static/css/join/join.css
src/main/resources/static/css/login/login.css
src/main/resources/static/html/login/login.html
src/main/resources/static/js/login/login.js

로그인 실패 시 실패 사유를 화면에 렌더링하는 기능 추가

feat: 로그인 실패 문구 보여주기 기능

---

build.gradle
src/main/java/com/fluffytime/userpage/service/UserPageService.java
src/main/resources/static/js/search/search.js

검색한 유저를 클릭하면 유저페이지로 이동하는 기능 추가+devtools활성화//TODO NoSuchElementException 오류 해결

feat: 검색한 유저를 클릭하면 유저페이지로 이동하는 기능 추가+devtools활성화

---

src/main/java/com/fluffytime/userpage/service/UserPageService.java

NoSuchElementException이 발생하던 코드에서 null값으로 처리해 오류를 대처

fix: NoSuchElementException이 발생하던 코드에서 null값으로 처리해 오류를 대처

---

src/main/resources/static/js/explore/explore.js
src/main/resources/static/js/post/postDetail.js

feat: 탐색에서 이미지 클릭시 상세정보창 이동 기능 추가

---

src/main/resources/static/css/post/createPost.css
src/main/resources/static/html/index.html
src/main/resources/static/js/post/createPost.js
src/main/resources/templates/index.html

Feature/게시물 통합

---

src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/templates/common/sidebar.html
src/main/resources/templates/explore/explore.html
src/main/resources/templates/main.html
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/post/postDetail.html
src/main/resources/templates/search/search.html
src/main/resources/templates/userpage/userpage.html

Feature/공통 fragment적용

---

src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/js/mypage/profiles/profile.js
src/main/resources/static/js/userpage/userpage.js
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/userpage/userpage.html

모달창 관련 변수가 겹쳐 css가 깨지는 현상이 발생했습니다.
- modal-overlay ->  profile-modal-overlay , userPage-modal-overlay
- modal -> profile-modal , userPage-modal
- modal-content -> profile-modal-content, userPage-modal-content

fix : 프로필, 유저페이지 모달창 id 이름 중복 변경

---

src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/css/post/createPost.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/static/js/mypage/mypage.js
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/userpage/userpage.html

- 유저페이지 imagePreview id명 수정
- 마이페이지에서 프로필 등록시 등록 안되는 에러 수정
- 유저페이지 모달 창이 띄어져 있는 현상 css 수정

fix : 마이페이지, 프로필 기타 버그 수정

---

src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/mypage/profiles/profile.js
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/userpage/userpage.html

- id가 게시글 모달창 id와 겹쳐 수정
- images -> mypage-images, profile-images, userpage-images

fix : 프로필, 마이페이지, 유저페이지에서 게시글 작성 버그 수정

---

src/main/resources/static/js/mypage/mypage.js
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/profiles/profile.html

머지후 프로필 사진이 등록이 안되는 버그를 수정했습니다.

fix : 머지후 프로필 사진 등록 버그 수정

---

src/main/java/com/fluffytime/comment/dto/CommentResponseDto.java
src/main/java/com/fluffytime/reply/dto/ReplyResponseDto.java
src/main/resources/static/css/comment/comment.css
src/main/resources/static/js/comment/comment.js
src/main/resources/templates/post/postDetail.html

게시글 상세보기 댓글 css 수정 및 프로필 사진 불러오기

fix: css 수정 및 댓글 프로필 사진 로직 수정

---

src/main/java/com/fluffytime/explore/controller/api/ExploreRestController.java

fix: 탐색요청 시 임시저장글은 보내지 않도록 수정

---

src/main/resources/static/js/search/search.js

검색어 없이 검색되지 않도록 수정 + 불필요한 코드 삭제

fix: 검색어 없이 검색되지 않도록 수정 + 불필요한 코드 삭제

---

src/main/java/com/fluffytime/auth/jwt/controller/JwtApiController.java
src/main/java/com/fluffytime/auth/jwt/exception/InvalidToken.java
src/main/java/com/fluffytime/auth/jwt/service/JwtService.java

🐛 Fix: 검증되지 않은 토큰 예외 수정

---

src/main/resources/templates/common/createModal.html
src/main/resources/templates/post/postDetail.html

fix: 모달 수정

---

src/main/java/com/fluffytime/comment/dto/CommentResponseDto.java
src/main/java/com/fluffytime/comment/service/CommentService.java
src/main/java/com/fluffytime/domain/Comment.java
src/main/java/com/fluffytime/domain/CommentLike.java
src/main/java/com/fluffytime/domain/User.java
src/main/java/com/fluffytime/like/controller/api/CommentLikeRestController.java
src/main/java/com/fluffytime/like/dto/CommentLikeRequestDto.java
src/main/java/com/fluffytime/like/dto/CommentLikeResponseDto.java
src/main/java/com/fluffytime/like/response/ErrorDto.java
src/main/java/com/fluffytime/like/service/CommentLikeService.java
src/main/java/com/fluffytime/repository/CommentLikeRepository.java
src/main/resources/static/css/comment/comment.css
src/main/resources/static/css/like/commentLike.css
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/like/commentLike.js
src/main/resources/templates/post/postDetail.html

✨ 댓글 좋아요 기능 구현

---

src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/java/com/fluffytime/userpage/controller/api/UserPageRestController.java
src/main/java/com/fluffytime/userpage/dao/UserBlockDao.java
src/main/java/com/fluffytime/userpage/response/BlockUserListDto.java
src/main/java/com/fluffytime/userpage/response/UserBlockResponseDto.java
src/main/java/com/fluffytime/userpage/response/UserPageInformationDto.java
src/main/java/com/fluffytime/userpage/service/UserPageService.java
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/static/js/mypage/profiles/profile.js
src/main/resources/static/js/userpage/blockUser.js
src/main/resources/static/js/userpage/userpage.js
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/userpage/userpage.html

유저페이지 차단 관련 기능을 구현합니다
- 유저 차단
- 유저 차단 해제
- 유저 차단 리스트 불러오기

Feature/유저페이지 차단 관련 기능 구현

---

build.gradle
src/main/java/com/fluffytime/mypage/response/MyPageInformationDto.java
src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/resources/static/js/mypage/mypage.js
src/main/resources/templates/mypage/mypage.html

마이페이지에서 저장됨을 클릭하면, 해당 유저가 저장한 북마크 게시물을 보여줍니다.

✨ 마이페이지 북마크 리스트 연결

---

src/main/java/com/fluffytime/user/dto/request/JoinRequest.java
src/main/java/com/fluffytime/user/dto/request/LoginUserRequest.java

🐛 Fix: 로그인 기본 생성자 문제 해결

---

src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/css/styles.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/userpage/userpage.html

마이페이지, 프로필편집 페이지, 유저페이지를 반응형 웹 디자인으로 업데이트 하였습니다.

Feature/유저페이지 

---

src/main/resources/static/css/styles.css
src/main/resources/static/js/home/home.js
src/main/resources/templates/common/sidebar.html

✨ 로그아웃 기능 추가

---

src/main/resources/static/js/like/postLike.js

🐛 게시글 좋아요 js 수정

---

src/main/java/com/fluffytime/user/service/LoginService.java
src/main/resources/static/js/common/logout.js
src/main/resources/static/js/home/home.js
src/main/resources/static/js/like/postLike.js
src/main/resources/templates/explore/explore.html
src/main/resources/templates/main.html
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/search/search.html

공통 로그아웃 js를 각 화면에 추가
비밀번호 바꿀 시 게시글이 사라지는 에러 수정

🐛 공통 로그아웃 및 비밀번호 바꾸기 시 에러 수정

---

src/main/java/com/fluffytime/bookmark/controller/api/BookmarkRestController.java

🔥 Fix: 북마크 name 추가

---

build.gradle
src/main/java/com/fluffytime/domain/Profile.java
src/main/java/com/fluffytime/domain/ProfileImages.java
src/main/java/com/fluffytime/mypage/controller/api/MyPageRestController.java
src/main/java/com/fluffytime/mypage/service/MyPageService.java
src/main/java/com/fluffytime/userpage/controller/api/UserPageRestController.java
src/main/java/com/fluffytime/userpage/service/UserPageService.java

1.  ResponseEntity<?> 와일드 카드 타입 지정
2. 프로필과 유저의 관계가 fetchType.LAZY로 변경
3. @NoArgsConstructor(access = AccessLevel.PROTECTED) 추가
4. 빌더로 코드가 길어지는 부분 인버터 메서드 생성하여 코드 축소
< 마이페이지에 생성된 메서드 목록 >
- List<PostDto> postList
- List<PostDto> bookmarkList
- MyPageInformationDto createResponseDto
- ProfileInformationDto createResponseDto
- ProfileImages createResponseDto
- void deleteCookie
< 유저페이지에 생성된 메서드 목록 > 
- List<PostDto> postList
- UserPageInformationDto createResponseDto
- List<Map<String, String>> BlockList
5. @Transactional(readOnly=true)는 속도가 더 느려 성능이 저하될 수 있으므로 @Transactional 변경

🎨 코드 리팩토링 2차

---

src/main/java/com/fluffytime/comment/service/CommentService.java
src/main/java/com/fluffytime/domain/Comment.java
src/main/java/com/fluffytime/domain/CommentLike.java
src/main/java/com/fluffytime/domain/PostLike.java
src/main/java/com/fluffytime/domain/Reply.java
src/main/java/com/fluffytime/domain/ReplyLike.java
src/main/java/com/fluffytime/like/controller/api/comment/CommentLikeRestController.java
src/main/java/com/fluffytime/like/controller/api/post/PostLikeRestController.java
src/main/java/com/fluffytime/like/controller/api/reply/ReplyLikeRestController.java
src/main/java/com/fluffytime/like/exception/LikeErrorCode.java
src/main/java/com/fluffytime/like/exception/LikeIsExists.java
src/main/java/com/fluffytime/like/exception/NoLikeFound.java
src/main/java/com/fluffytime/like/service/comment/CommentLikeService.java
src/main/java/com/fluffytime/like/service/post/PostLikeService.java
src/main/java/com/fluffytime/like/service/reply/ReplyLikeService.java
src/main/java/com/fluffytime/reply/service/ReplyService.java
src/main/resources/static/js/like/commentLike.js
src/main/resources/static/js/like/postLike.js
src/main/resources/static/js/like/replyLike.js

convert 메소드, 메소드 분리, fetch 설정 등 리팩토링

♻️ 댓글/답글/좋아요 리팩토링

---

src/main/java/com/fluffytime/explore/service/ExploreService.java
src/main/java/com/fluffytime/follow/controller/api/FollowRestController.java
src/main/java/com/fluffytime/follow/service/FollowService.java
src/main/java/com/fluffytime/search/service/SearchService.java

refactor: 검색,탐색,팔로우 리팩토링

---

src/main/java/com/fluffytime/domain/board/entity/Comment.java
src/main/java/com/fluffytime/domain/board/entity/CommentLike.java
src/main/java/com/fluffytime/domain/board/entity/PostLike.java
src/main/java/com/fluffytime/domain/board/entity/Reply.java
src/main/java/com/fluffytime/domain/board/entity/ReplyLike.java
src/main/java/com/fluffytime/domain/board/service/PostLikeService.java

컨버트 메소드 분리 및 엔티티 access 설정 리팩토링

♻️ Builder convert 메소드 분리 수정 및 access 설정

---

src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
src/main/java/com/fluffytime/domain/board/entity/Post.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/resources/static/css/post/postDetail.css
src/main/resources/static/js/post/createPost.js
src/main/resources/static/js/post/postDetail.js
src/main/resources/templates/common/tempModal.html
src/main/resources/templates/post/postDetail.html

기본으로 댓글 기능이 보이지만 토글에서 댓글 기능 해제를 누르면 댓글 기능이 안보이고 댓글 기능 설정을 누르면 댓글 기능이 보인다.
게시글 상세보기 토글을 수정해서 일반 사용자는 신고, 링크 복사 , 취소만 볼 수 있고 게시글 작성자는 삭제, 수정, 다른 사람에게 좋아요 수 숨기기, 댓글 기능 해제, 링크 복사, 취소가 보인다.
게시글 상세보기에 작성자 정보를 가져오는 코드를 수정해서 게시글 작성자가 프로필에서 등록한 프로필 사진, 닉네임, 펫 이름, 펫 성별, 펫 나이를 가져온다.

🎨 Fix: 게시물 상세보기 수정

---

src/main/resources/static/css/post/createPost.css
src/main/resources/static/js/post/createPost.js

임시저장 게시물 목록 & 이어쓰기 모달 깨짐 현상을 수정하였습니다.

🐛 Fix: 임시저장 게시물 목록 & 이어쓰기 모달 깨짐 현상을 수정하였습니다.

---

src/main/java/com/fluffytime/domain/board/controller/PostController.java
src/main/resources/static/css/post/PostEdit.css
src/main/resources/static/js/post/postDetail.js
src/main/resources/static/js/post/postEdit.js
src/main/resources/templates/post/postDetail.html
src/main/resources/templates/post/postEdit.html

-  게시글 상세보기 작성자 정보에 null, undefined 값에 대한 빈 문자열을 처리하여 none, 0으로 나오는 문제 해결했다.
- 게시글 상세화면에서 수정되는걸 수정화면을 만들었다.

🎨 Fix: 게시글수정 화면 추가

---

src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
src/main/java/com/fluffytime/domain/board/repository/TagPostRepository.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/TagService.java
src/main/resources/static/css/comment/comment.css
src/main/resources/static/css/post/postDetail.css
src/main/resources/static/js/post/createPost.js
src/main/resources/static/js/post/postDetail.js
src/main/resources/templates/post/postDetail.html

💄 Style: 게시물 상세보기 관련 UI 수정

---

src/main/java/com/fluffytime/domain/board/controller/PostController.java
src/main/java/com/fluffytime/domain/board/repository/PostRepository.java
src/main/java/com/fluffytime/domain/board/service/PostService.java

-임시저장 목록에 내가 쓴 임시저장 목록만 보이게 수정했다.
-임시저장 개수 20개까지 가능하고 그 이상은 오래 된 임시저장 게시글 순으로 삭제되게 수정했다.

🎨 Fix : 임시저장 글 목록 관련 수정

---

src/main/java/com/fluffytime/domain/user/controller/api/FollowRestController.java
src/main/java/com/fluffytime/domain/user/dto/response/FollowListResponse.java
src/main/java/com/fluffytime/domain/user/repository/FollowRepository.java
src/main/java/com/fluffytime/domain/user/service/FollowService.java
src/main/resources/static/js/follow/follow.js
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/userpage/userpage.html

✨ feat: 팔로우/팔로잉 목록 기초적인 기능 추가

---

src/main/java/com/fluffytime/domain/board/entity/Post.java
src/main/java/com/fluffytime/domain/board/service/CommentService.java
src/main/java/com/fluffytime/domain/notification/controller/NotificationController.java
src/main/java/com/fluffytime/domain/notification/controller/api/NotificationRestController.java
src/main/java/com/fluffytime/domain/notification/dto/request/NotificationRequest.java
src/main/java/com/fluffytime/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/fluffytime/domain/notification/entity/Notification.java
src/main/java/com/fluffytime/domain/notification/exception/NotificationNotFound.java
src/main/java/com/fluffytime/domain/notification/exception/codes/NotificationErrorCode.java
src/main/java/com/fluffytime/domain/notification/repository/NotificationRepository.java
src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
src/main/java/com/fluffytime/domain/user/dto/response/NotificationUserResponse.java
src/main/java/com/fluffytime/domain/user/entity/User.java
src/main/resources/static/css/notification/notification.css
src/main/resources/static/js/notification/notification.js
src/main/resources/templates/notification/notificationView.html

✨ 댓글 알림 기능 구현

---

src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/TagService.java
src/main/resources/static/css/post/PostEdit.css
src/main/resources/static/js/post/postDetail.js
src/main/resources/static/js/post/postEdit.js
src/main/resources/templates/post/postEdit.html

✨ Feat: 게시글 수정 시 태그 수정 로직 구현

---

src/main/java/com/fluffytime/domain/board/entity/Comment.java
src/main/java/com/fluffytime/domain/board/entity/Reply.java
src/main/java/com/fluffytime/domain/board/service/CommentLikeService.java
src/main/java/com/fluffytime/domain/board/service/PostLikeService.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/ReplyLikeService.java
src/main/java/com/fluffytime/domain/board/service/ReplyService.java
src/main/java/com/fluffytime/domain/notification/dto/request/NotificationRequest.java
src/main/java/com/fluffytime/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/fluffytime/domain/notification/entity/Notification.java
src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/resources/static/css/notification/notification.css
src/main/resources/templates/common/sidebar.html

답글/좋아요 알림 기능 추가 및 자신이 만든 알림은 보내지 않도록 추가

✨ 답글 좋아요 알림 기능 추가

---

src/main/java/com/fluffytime/domain/admin/controller/AdminController.java
src/main/java/com/fluffytime/domain/admin/interceptor/AdminCheckInterceptor.java
src/main/java/com/fluffytime/domain/user/controller/UserController.java
src/main/java/com/fluffytime/domain/user/controller/api/UserRestController.java
src/main/java/com/fluffytime/domain/user/entity/enums/RoleName.java
src/main/java/com/fluffytime/global/auth/jwt/dto/CustomUserDetails.java
src/main/java/com/fluffytime/global/auth/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/fluffytime/global/config/SecurityConfig.java
src/main/java/com/fluffytime/global/config/WebConfig.java
src/main/resources/static/css/styles.css
src/main/resources/static/js/auth/auth.js
src/main/resources/templates/common/sidebar.html

ROLE_ADMIN만 관리자 페이지 접근 가능하도록 구현 
interceptor를 이용하여 accesstoken 재발급 시 header에 관리자 여부 포함시킴 
이에 따라 관리자 유저만 관리자 페이지 접근 버튼 보이도록 구현

✨ Feat: 인가 페이지 접근 처리 & 유저 역할에 따른 관리자 페이지 접근 보여주기 구현

---

src/main/resources/templates/notification/notificationView.html

💄 사이드바 기능 수정

---

src/main/java/com/fluffytime/domain/admin/interceptor/AdminCheckInterceptor.java
src/main/java/com/fluffytime/domain/user/service/LoginService.java
src/main/java/com/fluffytime/global/auth/jwt/dto/CustomUserDetails.java
src/main/java/com/fluffytime/global/auth/jwt/filter/JwtAuthenticationFilter.java

🔥 Remove: 불필요한 log 제거

---

src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
src/main/resources/static/js/notification/notification.js

♻️ HikariPool 성능 문제 수정

---

src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/global/config/aws/S3Service.java
src/main/resources/static/js/post/createPost.js

- 임시저장된 글에서 사진과 동영상 안 나오는 오류 수정
- 임시저장 글 다시 임시저장해도 임시저장되게 수정
- 임시저장 글 목록 최신순으로 내림차순으로 수정

🐛 Fix: 임시저장 관련 수정

---

src/main/java/com/fluffytime/domain/admin/controller/AdminController.java
src/main/java/com/fluffytime/domain/admin/controller/api/StatisticsRestController.java
src/main/java/com/fluffytime/domain/admin/dto/DailyContentsCount.java
src/main/java/com/fluffytime/domain/admin/dto/DailyCount.java
src/main/java/com/fluffytime/domain/admin/dto/DailyUserCount.java
src/main/java/com/fluffytime/domain/admin/dto/response/DailyCountStatisticsResponse.java
src/main/java/com/fluffytime/domain/admin/service/PostStatisticsService.java
src/main/java/com/fluffytime/domain/admin/service/UserStatisticsService.java
src/main/java/com/fluffytime/domain/admin/util/convertor/StatisticsConvertor.java
src/main/java/com/fluffytime/domain/board/repository/PostRepository.java
src/main/java/com/fluffytime/domain/user/repository/UserRepository.java
src/main/java/com/fluffytime/global/config/SecurityConfig.java
src/main/resources/static/css/admin/common/adminStyles.css
src/main/resources/static/css/admin/common/sidebar.css
src/main/resources/static/css/admin/statistics/statistics.css
src/main/resources/static/css/admin/user/userManagementPage.css
src/main/resources/static/js/admin/statistics/user.js
src/main/resources/templates/admin/admin.html
src/main/resources/templates/admin/common/sidebar.html
src/main/resources/templates/admin/user/userManagementPage.html

관리자 페이지 중 통계 데이터를 보여주는 페이지 구현
- 일일 가입 유저 수
- 일일 콘텐츠 등록 수
- 실시간 알림 기능 추가 예정

✨ Feat: 관리자 페이지 구현 - 통계

---

src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
src/main/java/com/fluffytime/domain/board/dto/request/PostRequest.java
src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
src/main/java/com/fluffytime/domain/board/entity/Post.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/resources/static/css/post/postDetail.css
src/main/resources/static/js/post/createPost.js
src/main/resources/static/js/post/postDetail.js
src/main/resources/static/js/post/postEdit.js
src/main/resources/templates/common/createModal.html
src/main/resources/templates/post/postDetail.html
src/main/resources/templates/post/postEdit.html

-이미지 파일 사이즈 고화질도 가능하게 수정
-게시글에서 다른 사람에게 좋아요 수 숨기기/취소 기능 구현
-게시글 만들 때랑 수정할 때 다른 사람에게 좋아요 수 숨기기/댓글 기능 해제 할 수 있게 수정
-게시글 수정할 때 동영상은 안 보이는 에러 수정

✨ Feat: 다른 사람에게 좋아요 수 숨기기 기능 구현

---

src/main/java/com/fluffytime/domain/board/controller/ReelsController.java
src/main/java/com/fluffytime/domain/board/controller/api/ReelsRestController.java
src/main/java/com/fluffytime/domain/board/dto/response/ReelsResponse.java
src/main/java/com/fluffytime/domain/board/entity/Reels.java
src/main/java/com/fluffytime/domain/board/repository/ReelsRepository.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/ReelsService.java
src/main/resources/static/css/post/reels.css
src/main/resources/static/css/styles.css
src/main/resources/static/js/post/reels.js
src/main/resources/templates/common/sidebar.html
src/main/resources/templates/post/reels.html

-동영상을 필터링하여 릴스에 구성
-무한 스크롤
-자동 재생 및 반복 재생 기능
-작성자 프로필 정보(사진, 닉네임)
-게시물 내용

✨ Feat: 릴스 기능 구현

---

src/main/java/com/fluffytime/domain/board/controller/api/CommentRestController.java
src/main/java/com/fluffytime/domain/board/controller/api/MentionRestController.java
src/main/java/com/fluffytime/domain/board/controller/api/ReplyRestController.java
src/main/java/com/fluffytime/domain/board/dto/request/MentionRequest.java
src/main/java/com/fluffytime/domain/board/dto/response/MentionResponse.java
src/main/java/com/fluffytime/domain/board/entity/Comment.java
src/main/java/com/fluffytime/domain/board/entity/Mention.java
src/main/java/com/fluffytime/domain/board/entity/Post.java
src/main/java/com/fluffytime/domain/board/entity/Reply.java
src/main/java/com/fluffytime/domain/board/repository/MentionRepository.java
src/main/java/com/fluffytime/domain/board/service/CommentService.java
src/main/java/com/fluffytime/domain/board/service/MentionParser.java
src/main/java/com/fluffytime/domain/board/service/MentionService.java
src/main/java/com/fluffytime/domain/board/service/ReplyService.java
src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
src/main/java/com/fluffytime/domain/user/entity/User.java
src/main/resources/static/css/comment/comment.css
src/main/resources/static/css/post/createPost.css
src/main/resources/static/css/post/postDetail.css
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/like/commentLike.js
src/main/resources/static/js/like/postLike.js
src/main/resources/static/js/like/replyLike.js
src/main/resources/static/js/notification/notification.js
src/main/resources/static/js/post/createPost.js
src/main/resources/templates/common/createModal.html
src/main/resources/templates/post/postDetail.html

✨ 멘션 기능 추가

---

src/main/java/com/fluffytime/domain/board/dto/request/PostRequest.java
src/main/java/com/fluffytime/domain/board/entity/Post.java

🐛 Fix: post 엔티티 수정

---

build.gradle
src/main/java/com/fluffytime/domain/chat/exception/ChatErrorCode.java
src/main/java/com/fluffytime/domain/chat/exception/ChatRoomNotFound.java
src/main/java/com/fluffytime/domain/chat/service/ChatServcie.java
src/main/resources/static/css/chat/chat.css
src/main/resources/static/js/chat/chat.js
src/main/resources/static/js/mypage/profiles/profile.js
src/main/resources/templates/chat/chat.html

자바 스크립트 및 백엔드 코드를 리팩토링합니다. 
- 프로필 사진이 없을시 채팅에서 버그 수정
-  채팅을 보낼시 발신자만 채팅 목록에 최신 채팅 기록이 업데이트 되는 부분을 수신자 또한 동기화 되도록 수정

♻️ Ref : 채팅 기능 코드 리팩토링

---

src/main/java/com/fluffytime/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/fluffytime/domain/notification/entity/Notification.java
src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/java/com/fluffytime/domain/user/entity/User.java
src/main/java/com/fluffytime/domain/user/service/FollowService.java
src/main/resources/static/css/comment/comment.css
src/main/resources/static/css/notification/notification.css
src/main/resources/static/css/post/postDetail.css
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/notification/notification.js
src/main/resources/static/js/post/postDetail.js

♻️ 알림 관련 코드 리팩토링

---

src/main/java/com/fluffytime/domain/board/service/CommentService.java
src/main/java/com/fluffytime/domain/board/service/MentionService.java
src/main/java/com/fluffytime/domain/board/service/ReplyService.java
src/main/java/com/fluffytime/domain/chat/service/ChatServcie.java
src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
src/main/java/com/fluffytime/domain/user/service/LoginService.java

♻️ 트랜잭션 관련 리팩토링

---

src/main/java/com/fluffytime/domain/board/controller/ReelsController.java
src/main/java/com/fluffytime/domain/board/controller/api/ReelsRestController.java
src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
src/main/java/com/fluffytime/domain/board/dto/response/ReelsResponse.java
src/main/java/com/fluffytime/domain/board/entity/Post.java
src/main/java/com/fluffytime/domain/board/entity/PostImages.java
src/main/java/com/fluffytime/domain/board/entity/Reels.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/ReelsService.java
src/main/resources/static/css/post/reels.css
src/main/resources/static/js/post/reels.js
src/main/resources/templates/common/sidebar.html
src/main/resources/templates/post/reels.html

🐛 Fix: 릴스 엔티티 수정

---

src/main/java/com/fluffytime/domain/board/service/ReelsService.java
src/main/resources/static/css/home/home.css
src/main/resources/static/js/explore/explore.js
src/main/resources/static/js/home/home.js
src/main/resources/templates/post/reels.html

🚑️ Hotfix: 동영상 엑스박스 표시 문제 해결

---

build.gradle
src/main/java/com/fluffytime/domain/user/dto/response/MyPageInformationResponse.java
src/main/java/com/fluffytime/domain/user/dto/response/UserPageInformationResponse.java
src/main/java/com/fluffytime/domain/user/service/MyPageService.java
src/main/java/com/fluffytime/domain/user/service/UserPageService.java
src/main/resources/static/css/mypage/profiles/profile.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/mypage/profiles/profile.js
src/main/resources/static/js/userpage/userpage.js
src/main/resources/templates/chat/chat.html
src/main/resources/templates/mypage/profiles/profile.html
src/main/resources/templates/userpage/userpage.html

1. **유저 페이지 동영상 스타일 수정**
- 유저 페이지 내 동영상의 CSS 스타일을 수정하여 레이아웃 및 디자인을 개선합니다.
2. **프로필 편집 시 유저명 한글 입력 제한**
- 프로필 편집 페이지에서 유저명 입력 시 한글이 포함되지 않도록 패턴 검사 후 제한합니다.
3. **마이페이지 소개글 표시 오류 수정**
- 마이페이지에서 소개글이 정상적으로 표시되지 않는 문제를 해결합니다.
4. **마이페이지 및 채팅 페이지의 로그아웃 버튼 수정**
- 마이페이지 및 채팅 페이지에서 로그아웃 버튼이 동작하지 않는 문제를 수정합니다.
5. **프로필 편집 시 유저명 중복 확인 로직 수정**
- 유저명 외의 다른 필드를 변경할 때, 유저명 중복 확인 없이도 변경이 가능했던 문제를 수정합니다.
6. **마이페이지 및 유저 페이지 게시글 최신순 정렬**
- 마이페이지 및 유저 페이지에서 게시글이 최신순으로 표시되도록 정렬 방식을 변경합니다.

🚑️ Hotfix:마이페이지&유저페이지 버그 수정

---

src/main/java/com/fluffytime/domain/search/controller/api/ExploreRestController.java
src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/css/styles.css
src/main/resources/static/css/userpage/userpage.css
src/main/resources/static/js/home/home.js
src/main/resources/templates/common/sidebar.html
src/main/resources/templates/mypage/mypage.html

💄 전체적인 css 및 js 수정

---

src/main/java/com/fluffytime/global/common/smtp/builder/CertificationEmailContent.java
src/main/java/com/fluffytime/global/common/smtp/builder/ChangePasswordEmailContent.java
src/main/resources/application.yml
src/main/resources/static/css/post/reels.css

도메인 경로 https 로 수정 & 릴스 사이드바 세로 선 안보임 수정

🐛 Fix: 도메인 경로 수정 & 릴스 css 수정

---

src/main/resources/static/js/common/logout.js

🐛 Fix: 로그아웃 js 리다이렉션 제거

---

src/main/java/com/fluffytime/domain/user/service/LoginService.java
src/main/resources/static/js/common/logout.js

🚑️ Hotfix: 로그아웃 리디렉션 문제 수정

---

src/main/resources/static/js/admin/statistics/notification.js
src/main/resources/static/js/auth/auth.js
src/main/resources/static/js/chat/chat.js
src/main/resources/templates/main.html

Hotfix: 관리자 알림 js 경로 수정

---

src/main/java/com/fluffytime/domain/admin/controller/api/StatisticsRestController.java
src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
src/main/resources/static/js/admin/statistics/user.js

StatisticsRestController Http Method 변경

♻️ Refactor: StatisticsRestController Http Method 변경

---

src/main/resources/static/css/post/reels.css
src/main/resources/static/js/post/reels.js

✨ Feat: 릴스에 좋아요 기능 추가

---

src/main/java/com/fluffytime/domain/chat/service/ChatServcie.java
src/main/java/com/fluffytime/global/config/SecurityConfig.java
src/main/resources/static/css/post/reels.css
src/main/resources/static/js/notification/notification.js
src/main/resources/static/js/post/reels.js

좋아요, 북마크, 더보기를 하나의 태그 안에 넣어서 관리

🐛 Fix: reels 좋아요, 북마크 버튼 작동 안함 수정

---

build.gradle
src/main/resources/static/js/mypage/profiles/profile.js

프로필 편집시 유저명을 변경하지 않아도 유저명이 변경되었습니다 라고 알림창이 뜨는 현상 수정

🚑️ Hotfix : 프로필 편집시 버그 수정

---

src/main/resources/static/js/home/home.js
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/userpage/userpage.js

메인 홈페이지에서 동영상 게시물이 자동적으로 재생이 안되는 버그를 수정합니다.

🐛 Fix : 메인 홈에 동영상 자동 재생 안되는 문제 해결

---

src/main/java/com/fluffytime/domain/notification/controller/api/NotificationRestController.java
src/main/resources/static/css/styles.css
src/main/resources/static/js/notification/notification.js
src/main/resources/templates/common/sidebar.html

알림 전체 알림을 실시간으로 보내주는 1차 작업 리팩토링

♻️ 알림 실시간 전체 알림 1차 리팩토링

---

src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/domain/board/service/ReelsService.java

♻️ Refactor: 메소드 분리

---

.github/ISSUE_TEMPLATE/♻️refactor.md
.github/ISSUE_TEMPLATE/💄style.md

docs: update issue template

---

src/main/java/com/fluffytime/domain/board/service/PostService.java
src/main/java/com/fluffytime/global/config/SecurityConfig.java
src/main/java/com/fluffytime/global/config/WebConfig.java

✨ Feature: React 연결 세팅

---

.github/workflows/cicd.yml
build.gradle

Feat: github action yml설정

---

.github/workflows/cicd.yml

Feat: github action yml설정 변경
